## -*- encoding: utf-8 -*-
## This file (master-document.sagetex.sage) was *autogenerated* from master-document.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('master-document', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
